*==============================================
*N-EMOS 3T pinout: D,G,S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*==============================================
*MicroCode Engineering

*Default N-Channel MOSFET
.PARAM MNMOS~ File:Mcemos.lib

*25V  20mA 150 ohm
.PARAM M2N3796 File:Mcemos.lib

*25V  20mA 150 ohm
.PARAM M2N3797 File:Mcemos.lib

*25V  30mA 100 ohm
.PARAM M2N4351 File:Mcemos.lib

*55V 43A .0279ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI1010G File:Mcemos.lib

*100V 4A .267ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI510G File:Mcemos.lib

*100V 7A .167ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI520G File:Mcemos.lib

*100V 10A .124ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI530G File:Mcemos.lib

*100V 17A .0706ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI540G File:Mcemos.lib

*100V 21A .0571ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI1310G File:Mcemos.lib

*200V 4A .293ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI620G File:Mcemos.lib

*200V 6A .203ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI630G File:Mcemos.lib

*200V 10A .122ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI640G File:Mcemos.lib

*250V 2A .571ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI614G File:Mcemos.lib

*250V 3A .353ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI624G File:Mcemos.lib

*250V 6A .214ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI634G File:Mcemos.lib

*250V 8A .152ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI644G File:Mcemos.lib

*400V 3A .462ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI720G File:Mcemos.lib

*400V 4A .324ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI730G File:Mcemos.lib

*400V 5A .222ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI740G File:Mcemos.lib

*450V 3A .353ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI734G File:Mcemos.lib

*450V 5A .245ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI744G File:Mcemos.lib

*500V 2A .571ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI820G File:Mcemos.lib

*500V 3A .387ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI830G File:Mcemos.lib

*500V 5A .261ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI840G File:Mcemos.lib

*=======================================
*TEMIC Semiconductors

*Tem 30V 4.2A TrenchFET pkg:TSOP-6
.PARAM XSi3454DV File:Siliconx.lib
