*==============================================
*NJFET Pinout: 1=D, 2=G, 3=S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default N-Ch J-FET parameters pkg:TO-92B 3,1,2
.PARAM JNJFET~ File:Mcejfets.lib

*40V 30mA Depl pkg:TO-18 2,3,1
.PARAM J2N4393 File:Mcejfets.lib

*25V  25mA  250 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5457 File:Mcejfets.lib

*25V  25mA  250 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5459 File:Mcejfets.lib

*25V  30mA  175 ohm Depl pkg:TO-92B 3,1,2
.PARAM J2N5484 File:Mcejfets.lib

*25V  30mA  28.8ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5486 File:Mcejfets.lib

*30V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5640 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5668 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5669 File:Mcejfets.lib

*25V  20mA  35.3ohm  Depl pkg:TO-92B 3,1,2
.PARAM J2N5670 File:Mcejfets.lib

*30V 150mA Depl pkg:TO-92B 1,2,3
.PARAM J2N4416 File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244A File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244B File:Mcejfets.lib

*30V 50mA Depl pkg:TO-92B 1,2,3
.PARAM JBF244C File:Mcejfets.lib

