*==============================================
*P-EMOS 3T pinout: D,G,S
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*==============================================
*MicroCode Engineering

*Default P-Channel MOSFET
.PARAM MPMOS~ File:Mcemos.lib

*100V 4A 1.2 ohms HEXFET pkg:TO-220 2,1,3
.PARAM XIRF9510 File:Mcemos.lib

*60V 5A .226ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z14G File:Mcemos.lib

*60V 8A .141ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z24G File:Mcemos.lib

*60V 12A .1ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9Z34G File:Mcemos.lib

*100V 5A .231ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9520G File:Mcemos.lib

*100V 8A .156ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9530G File:Mcemos.lib

*100V 11A .109ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9540G File:Mcemos.lib

*200V 3A .4ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9620G File:Mcemos.lib

*200V 4A .279ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9630G File:Mcemos.lib

*200V 6A .197ohm Power MOSFET pkg:TO-220 2,3,1
.PARAM XIRFI9640G File:Mcemos.lib
