*==============================================
*PNP Trans pinout: C,B,E
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*========================================
*MicroCode Engineering

*Default PNP BJT pkg:TO-92B 1,2,3
.PARAM QPNP~ File:Mcebjt.lib

*Si 600mW 60V 600mA 300MHz pkg:TO-5 3,2,1
.PARAM Q2N2905A File:Mcebjt.lib

*Si 1.8W 60V 600mA 200MHz pkg:TO-18 3,2,1
.PARAM Q2N2907A File:Mcebjt.lib

*Si 360mW 60V 200mA 340MHz pkg:TO-18 3,2,1
.PARAM Q2N3251A File:Mcebjt.lib

*Si 1W 40V 1A 200MHz pkg:TO-5 3,2,1
.PARAM Q2N3467 File:Mcebjt.lib

*Si 1W 50V 1A 180MHz pkg:TO-5 3,2,1
.PARAM Q2N3468 File:Mcebjt.lib

*Si 360mW 60V 50mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N3799 File:Mcebjt.lib

*Si 310mW 40V 200mA 200MHz pkg:TO-92B 1,2,3
.PARAM Q2N3905 File:Mcebjt.lib

*Si 625mW 40V 200mA 250MHz pkg:TO-92B 1,2,3
.PARAM Q2N3906 File:Mcebjt.lib

*Si 360mW 45V 200mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N3964 File:Mcebjt.lib

*Si 310mW 40V 600mA 150MHz pkg:TO-92B 1,2,3
.PARAM Q2N4402 File:Mcebjt.lib

*Si 625mW 40V 600mA 250MHz pkg:TO-92B 1,2,3
.PARAM Q2N4403 File:Mcebjt.lib

*Si 625mW 50V 50mA 400MHz pkg:TO-92B 1,2,3
.PARAM Q2N5087 File:Mcebjt.lib

*Si 625mW 150V 600mA 300MHz pkg:TO-92B 1,2,3
.PARAM Q2N5401 File:Mcebjt.lib

*Si 500mW 300V 500mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N6433 File:Mcebjt.lib

*Si 625mW 350V 500mA 84MHz pkg:TO-92B 1,2,3
.PARAM Q2N6520 File:Mcebjt.lib

*Si 625mW 80V 500mA 155MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA56 File:Mcebjt.lib

*Si 625mW 300V 500mA 95MHz pkg:TO-92B 1,2,3
.PARAM QMPSA92 File:Mcebjt.lib

*Si 625mW 25V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4126 File:Mcebjt.lib

*Si 350mW 12V 200mA 700MHz Switching pkg:TO-92B 1,2,3
.PARAM Q2N4258 File:Mcebjt.lib

*Si 625mW 50V 100mA 40MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5086 File:Mcebjt.lib

*Si 625mW 50V 100mA 40MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5087 File:Mcebjt.lib

*Si 350mW 15V 200mA 700MHz Switching pkg:TO-92B 1,2,3
.PARAM Q2N5771 File:Mcebjt.lib

*Si 625mW 30V 200mA 250MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N4125 File:Mcebjt.lib

*Si 625mW 120V 600mA 250MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5400 File:Mcebjt.lib

*Si 625mW 300V 500mA 120MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6519 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA55 File:Mcebjt.lib

*Si 625mW 40V 100mA 100MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA70 File:Mcebjt.lib

*Si 625mW 200V 500mA 80MHz HiVolt pkg:TO-92B 1,2,3
.PARAM QMPSA93 File:Mcebjt.lib

*Si 600mW 40V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2904 File:Mcebjt.lib

*Si 600mW 60V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2904A File:Mcebjt.lib

*Si 600mW 40V 600mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2905 File:Mcebjt.lib

*Si 400mW 40V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2906 File:Mcebjt.lib

*Si 400mW 60V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2906A File:Mcebjt.lib

*Si 400mW 40V 600mA 250MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2907 File:Mcebjt.lib

*Si 1W 40V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3244 File:Mcebjt.lib

*Si 360mW 40V 200mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3250 File:Mcebjt.lib

*Si 360mW 40V 200mA 350MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3251 File:Mcebjt.lib

*Si 400mW 120V 100mA 200MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N3497 File:Mcebjt.lib

*Si 360mW 12V 200mA 800MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N3546 File:Mcebjt.lib

*Si 1W 140V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3634 File:Mcebjt.lib

*Si 1W 140V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3635 File:Mcebjt.lib

*Si 1W 175V 1A 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3636 File:Mcebjt.lib

*Si 1W 175V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3637 File:Mcebjt.lib

*Si 360mW 80V 200mA 257MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N3963 File:Mcebjt.lib

*Si 800mW 60V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4032 File:Mcebjt.lib

*Si 800mW 80V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4033 File:Mcebjt.lib

*Si 1W 65V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4036 File:Mcebjt.lib

*Si 1W 40V 1A 115MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4037 File:Mcebjt.lib

*Si 1.25W 80V 1A 350MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4405 File:Mcebjt.lib

*Si 1.25W 80V 2A 450MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4407 File:Mcebjt.lib

*Si 1W 250V 50mA 110MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N4931 File:Mcebjt.lib
