*==============================================
*Varactor Diode Pinout: 1=A, 2=K
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*==============================================
*Zetex

*ZTX 28V Cd=1.80pF/2.80pF Si pkg:SOT-23 3,1
.PARAM DBBY31 File:Zetex.lib

*ZTX 28V Cd=4.30pF/6.00pF Si pkg:SOT-23 3,1
.PARAM DBBY40 File:Zetex.lib
