*==============================================
*Diode Pinout: 1=A, 2=K
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default diode PARAMeter values pkg:DIODE0.4 A,K
.PARAM DDIODE~ File:Mcediode.lib

*==============================================
*MicroCode Engineering

*60V 85mA Ge Signal Diode pkg:DIODE0.4 A,K
.PARAM D1N34 File:Mcediode.lib

*100V 80mA Si Switching Diode pkg:DIODE0.4 A,K
.PARAM D1N914 File:Mcediode.lib

*75V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N914A File:Mcediode.lib

*75V 100mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N914B File:Mcediode.lib

*50V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4001 File:Mcediode.lib

*100V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4002 File:Mcediode.lib

*200V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4003 File:Mcediode.lib

*400V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4004 File:Mcediode.lib

*600V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4005 File:Mcediode.lib

*800V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4006 File:Mcediode.lib

*1000V 1A Si GenPurpose Diode pkg:DIODE0.4 A,K
.PARAM D1N4007 File:Mcediode.lib

*75V 10mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4148 File:Mcediode.lib

*75V 10mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4149 File:Mcediode.lib

*50V 200mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4150 File:Mcediode.lib

*50V 50mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4151 File:Mcediode.lib

*30V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4152 File:Mcediode.lib

*50V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4153 File:Mcediode.lib

*25V 30mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4154 File:Mcediode.lib

*15V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4244 File:Mcediode.lib

*50V 10mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4305 File:Mcediode.lib

*20V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4446 File:Mcediode.lib

*20V 20mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4447 File:Mcediode.lib

*20V 100mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4448 File:Mcediode.lib

*50V 10mA Si Computer Diode pkg:DIODE0.4 A,K
.PARAM D1N4454 File:Mcediode.lib

*400V 1A Si Rectifier pkg:DIODE0.4 A,K
.PARAM D1N4934 File:Mcediode.lib

*175V 100mA Si HiVoltage Diode pkg:DIODE0.4 A,K
.PARAM D1N4938 File:Mcediode.lib

*50V 3A Si Rectifier pkg:DO-201 1,2
.PARAM D1N5400 File:Mcediode.lib

*100V 3A Si Rectifier pkg:DO-201 1,2
.PARAM D1N5401 File:Mcediode.lib

*200V 3A Si Rectifier pkg:DO-201 1,2
.PARAM D1N5402 File:Mcediode.lib

*400V 3A Si Rectifier pkg:DO-201 1,2
.PARAM D1N5404 File:Mcediode.lib

*600V 3A Si Rectifier pkg:DO-201 1,2
.PARAM D1N5406 File:Mcediode.lib

*800V 3000mA 3us Si Diode pkg:DIODE0.4 A,K
.PARAM D1N5407 File:Mcediode.lib

*1000V 3000mA 3us Si Diode pkg:DIODE0.4 A,K
.PARAM D1N5408 File:Mcediode.lib

