*==============================================
*NPN Trans Pinout: C,B,E
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*=========================================
*MicroCode Engineering

*Default NPN BJT pkg:TO-92B 1,2,3
.PARAM QNPN~ File:Mcebjt.lib

*pkg:TO-92B 1,2,3
.PARAM QQNPN File:Mcebjt.lib

*Si 800mW 40V 800mA 350MHz GenPurp pkg:TO-5 3,2,1
.PARAM Q2N2219A File:Mcebjt.lib

*Si 500mW 40V 800mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2222A File:Mcebjt.lib

*Si 360mW 15V 500mA 600MHz Switching pkg:TO-18 3,2,1
.PARAM Q2N2369A File:Mcebjt.lib

*Si 360mW 60V 50mA 100MHz pkg:TO-18 3,2,1
.PARAM Q2N2484 File:Mcebjt.lib

*Si 800mW 80V 1A 190MHz pkg:TO-5 3,2,1
.PARAM Q2N3019 File:Mcebjt.lib

*Si 5W 40V 700mA 185MHz pkg:TO-5 3,2,1
.PARAM Q2N3053 File:Mcebjt.lib

*Si 115W 70V 15A 20kHz pkg:TO-3 3,2,1
.PARAM Q2N3055 File:Mcebjt.lib

*Si 1W 150V 300mA 283MHz pkg:TO-5 3,2,1
.PARAM Q2N3501 File:Mcebjt.lib

*Si 1W 50V 3A 60MHz pkg:TO-5 3,2,1
.PARAM Q2N3507 File:Mcebjt.lib

*Si 500mW 80V 1A 190MHz pkg:TO-18 3,2,1
.PARAM Q2N3700 File:Mcebjt.lib

*Si 625mW 40V 200mA 300MHz pkg:TO-92B 1,2,3
.PARAM Q2N3904 File:Mcebjt.lib

*Si 360mW 40V 200mA 346MHz pkg:TO-18 3,2,1
.PARAM Q2N3947 File:Mcebjt.lib

*Si 625mW 40V 600mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4401 File:Mcebjt.lib

*Si 625mW 160V 600mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5551 File:Mcebjt.lib

*Si 500mW 300V 50mA 300MHz pkg:TO-18 3,2,1
.PARAM Q2N6431 File:Mcebjt.lib

*Si 625mW 350V 500mA 200MHz pkg:TO-92B 1,2,3
.PARAM Q2N6517 File:Mcebjt.lib

*Si 625mW 25V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4124 File:Mcebjt.lib

*Si 625mW 30V 100mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5088 File:Mcebjt.lib

*Si 625mW 25V 100mA 50MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5089 File:Mcebjt.lib

*Si 625mW 50V 100mA 30MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N5210 File:Mcebjt.lib

*Si 625mW 300V 200mA 50MHz HiVoltAmp pkg:TO-92B 1,2,3
.PARAM QMPSA42 File:Mcebjt.lib

*Si 625mW 200V 200mA 50MHz HiVoltAmp pkg:TO-92B 1,2,3
.PARAM QMPSA43 File:Mcebjt.lib

*Si 625mW 80V 500mA 219MHz GenPurp pkg:TO-92B 1,2,3
.PARAM QMPSA06 File:Mcebjt.lib

*Si 350mW 40V 100mA 125MHz pkg:TO-92B 1,2,3
.PARAM QMPSA17 File:Mcebjt.lib

*Si 625mW 45V 200mA 450MHz pkg:TO-92B 1,2,3
.PARAM QMPSA18 File:Mcebjt.lib

*Si 625mW 400V 300mA 200MHz pkg:TO-92B 1,2,3
.PARAM QMPSA44 File:Mcebjt.lib

*Si 625mW 40V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N3903 File:Mcebjt.lib

*Si 625mW 30V 200mA 250MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4123 File:Mcebjt.lib

*Si 350mW 15V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4264 File:Mcebjt.lib

*Si 350mW 12V 200mA 300MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4265 File:Mcebjt.lib

*Si 625mW 40V 600mA 200MHz GenPurp pkg:TO-92B 1,2,3
.PARAM Q2N4400 File:Mcebjt.lib

*Si 625mW 80V 250mA 100MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N4410 File:Mcebjt.lib

*Si 625mW 50V 50mA 30MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5209 File:Mcebjt.lib

*Si 625mW 140V 600mA 200MHz Amp pkg:TO-92B 1,2,3
.PARAM Q2N5550 File:Mcebjt.lib

*Si 625mW 250V 500mA 100MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6515 File:Mcebjt.lib

*Si 625mW 300V 500mA 100MHz HiVolt pkg:TO-92B 1,2,3
.PARAM Q2N6516 File:Mcebjt.lib

*Si 625mW 60V 500mA 150MHz Amp pkg:TO-92B 1,2,3
.PARAM QMPSA05 File:Mcebjt.lib

*Si 350mW 40V 100mA 150MHz Chopper pkg:TO-92B 1,2,3
.PARAM QMPSA16 File:Mcebjt.lib

*Si 1.2W 45V 30mA 60MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N930 File:Mcebjt.lib

*Si 1.2W 45V 30mA 90MHz Amp pkg:TO-18 3,2,1
.PARAM Q2N930A File:Mcebjt.lib

*Si 1.2W 80V 500mA 90MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N1893 File:Mcebjt.lib

*Si 1W 65V 1A 90MHz Amp pkg:TO-39 3,2,1
.PARAM Q2N2102 File:Mcebjt.lib

*Si 800mW 40V 800mA 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2218A File:Mcebjt.lib

*Si 800mW 30V 800mA 300MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N2219 File:Mcebjt.lib

*Si 400mW 30V 800mA 300MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2222 File:Mcebjt.lib

*Si 1W 45V 1A 250MHz Amp pkg:TO-39 3,2,1
.PARAM Q2N2270 File:Mcebjt.lib

*Si 360mW 15V 200mA 500MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N2369 File:Mcebjt.lib

*Si 500mW 65V 1A 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2895 File:Mcebjt.lib

*Si 500mW 90V 1A 150MHz GenPurp pkg:TO-18 3,2,1
.PARAM Q2N2896 File:Mcebjt.lib

*Si 800mW 80V 1A 250MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3020 File:Mcebjt.lib

*Si 1W 60V 700mA 150MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3053A File:Mcebjt.lib

*Si 1W 150V 300mA 200MHz GenPurp pkg:TO-39 3,2,1
.PARAM Q2N3500 File:Mcebjt.lib

*Si 500mW 40V 1A 400MHz Switch pkg:TO-18 3,2,1
.PARAM Q2N4014 File:Mcebjt.lib
