*===============================
*Schottky Diode Pinout: 1=A, 2=K
*===============================

*Default schottky diode parameters pkg:DO-41 1,2
.PARAM DSKYDIODE~ File:Mcediode.lib

*MCE 30V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ03 File:Mcediode.lib

*MCE 40V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ04 File:Mcediode.lib

*MCE 50V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ05 File:Mcediode.lib

*MCE 60V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ06 File:Mcediode.lib

*MCE 90V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ09 File:Mcediode.lib

*MCE 100V 1.1A pkg:DIODE0.4 A,K
.PARAM D11DQ10 File:Mcediode.lib

*MCE 40V 30A pkg:DIODE0.4 A,K
.PARAM D1N5828 File:Mcediode.lib

*MCE 40V 60A pkg:DIODE0.4 A,K
.PARAM D1N5834 File:Mcediode.lib

*MCE 30V 25A pkg:DIODE0.4 A,K
.PARAM D1N6095 File:Mcediode.lib

*MCE 40V 25A pkg:DIODE0.4 A,K
.PARAM D1N6096 File:Mcediode.lib

*MCE 30V 50A pkg:DIODE0.4 A,K
.PARAM D1N6097 File:Mcediode.lib

*MCE 40V 50A pkg:DIODE0.4 A,K
.PARAM D1N6098 File:Mcediode.lib

*MCE 45V 25A pkg:DIODE0.4 A,K
.PARAM D1N6391 File:Mcediode.lib

*MCE 45V 60A pkg:DIODE0.4 A,K
.PARAM D1N6392 File:Mcediode.lib

