*==============================================
*Zener Diode Pinout 1=A, 2=K
*Copyright (c) 1997 MicroCode Engineering, Inc.
*All Rights Reserved
*==============================================

*Default Zener 10V @ 10mA pkg:DIODE0.4 A,K
.PARAM DZENER~ File:Mcediode.lib

*3.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N746 File:Mcediode.lib

*3.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N747 File:Mcediode.lib

*3.9V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N748 File:Mcediode.lib

*4.3V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N749 File:Mcediode.lib

*4.7V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N750 File:Mcediode.lib

*5.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N751 File:Mcediode.lib

*5.6V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N752 File:Mcediode.lib

*6.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N753 File:Mcediode.lib

*6.8V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N754 File:Mcediode.lib

*7.5V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N755 File:Mcediode.lib

*8.2V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N756 File:Mcediode.lib

*9.1V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N757 File:Mcediode.lib

*10V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N758 File:Mcediode.lib

*12V 500mW Si Zener pkg:DIODE0.4 A,K
.PARAM D1N759 File:Mcediode.lib

*3.3V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4728 File:Mcediode.lib

*3.6V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4729 File:Mcediode.lib

*3.9V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4730 File:Mcediode.lib

*4.3V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4731 File:Mcediode.lib

*4.7V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4732 File:Mcediode.lib

*5.1V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4733 File:Mcediode.lib

*5.6V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4734 File:Mcediode.lib

*6.2V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4735 File:Mcediode.lib

*6.8V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4736 File:Mcediode.lib

*7.5V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4737 File:Mcediode.lib

*8.2V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4738 File:Mcediode.lib

*9.1V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4739 File:Mcediode.lib

*10V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4740 File:Mcediode.lib

*11V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4741 File:Mcediode.lib

*12V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4742 File:Mcediode.lib

*13V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4743 File:Mcediode.lib

*15V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4744 File:Mcediode.lib

*16V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4745 File:Mcediode.lib

*18V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4746 File:Mcediode.lib

*20V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4747 File:Mcediode.lib

*22V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4748 File:Mcediode.lib

*24V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4749 File:Mcediode.lib

*27V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4750 File:Mcediode.lib

*30V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4751 File:Mcediode.lib

*33V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4752 File:Mcediode.lib

*36V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4753 File:Mcediode.lib

*39V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4754 File:Mcediode.lib

*43V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4755 File:Mcediode.lib

*47V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4756 File:Mcediode.lib

*51V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4757 File:Mcediode.lib

*56V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4758 File:Mcediode.lib

*62V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4759 File:Mcediode.lib

*68V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4760 File:Mcediode.lib

*75V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4761 File:Mcediode.lib

*82V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4762 File:Mcediode.lib

*91V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4763 File:Mcediode.lib

*100V 1W Si Zener pkg:DIODE0.4 A,K
.PARAM D1N4764 File:Mcediode.lib
